// Compile-time check that the local schema (schema.ts) matches Postgres (database.types.ts,
// generated by `pnpm db:types`). A missing, extra or renamed column fails `pnpm typecheck`.
import type { Database } from './database.types';
import type { LocalDatabase, SyncedTableName } from './schema';

type Postgres = Database['public']['Tables'];
type Equal<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;
type Expect<T extends true> = T;

/** Columns of a Postgres table as synced: every column, renamed or skipped as the sync config does. */
type SyncedColumns<T extends SyncedTableName> = T extends 'permissions'
  ? // SELECT key AS id, module, sort_order FROM permissions
    'id' | 'module' | 'sort_order'
  : keyof Postgres[T]['Row'];

type LocalColumns<T extends SyncedTableName> = keyof LocalDatabase[T];

// `_metadata` is a local-only column PowerSync adds for authored tables.
type Matches<T extends SyncedTableName> = Equal<
  Exclude<LocalColumns<T>, '_metadata'>,
  SyncedColumns<T>
>;

export type SchemaDriftCheck = [
  Expect<Matches<'branches'>>,
  Expect<Matches<'roles'>>,
  Expect<Matches<'permissions'>>,
  Expect<Matches<'role_permissions'>>,
  Expect<Matches<'staff_users'>>,
  Expect<Matches<'staff_branches'>>,
  Expect<Matches<'staff_branch_access'>>,
  Expect<Matches<'devices'>>,
  Expect<Matches<'settings'>>,
];
