-- Devices (each reception PC, tablet or browser running the app) and settings.

-- Devices -------------------------------------------------------------------------------------

-- A device belongs to one branch, and that branch decides what it syncs. Its code is the D03 in
-- receipt numbers (B1-D03-000457): unique within the branch and never reused, because old receipts
-- carry it. Registered online with register_device().
create table public.devices (
  -- Generated by the device itself.
  id uuid primary key,
  branch_id uuid not null references public.branches (id),
  code text not null check (code ~ '^D[0-9]{2,3}$'),
  name text not null check (app.is_clean_text(name, 60)),
  platform text not null check (platform in ('web', 'android', 'windows')),
  -- Language before anyone logs in, and for staff without their own choice. Empty: Kurdish.
  default_language public.language_code,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  deleted_at timestamptz,
  unique (branch_id, code)
);

-- What each device last reported when online, so a manager can see devices with unsynced data
-- (alert after 24 hours). Kept apart from devices so these frequent writes don't touch the
-- device's own row. Written only by device_heartbeat(); not audited.
create table public.device_status (
  device_id uuid primary key references public.devices (id),
  last_seen_at timestamptz not null,
  -- The staff member signed in at the time.
  last_seen_by uuid,
  app_version text check (length(app_version) <= 40),
  -- Local changes waiting to upload, and when the oldest of them was made.
  pending_changes integer not null default 0 check (pending_changes >= 0),
  pending_since timestamptz
);

create trigger read_only before update on public.devices
  for each row execute function app.read_only_columns('id', 'branch_id', 'code');
create trigger stamp before insert or update on public.devices
  for each row execute function app.stamp_row();
create trigger audit after insert or update or delete on public.devices
  for each row execute function app.audit_row();

alter table public.devices enable row level security;
alter table public.device_status enable row level security;
revoke all on table public.devices, public.device_status from anon, authenticated;
grant all on table public.devices, public.device_status to service_role;

-- Staff see the devices of their branches; devices.manage renames them, sets their language, and
-- deactivates them. New devices come only from register_device().
grant select, update on table public.devices to authenticated;
grant select on table public.device_status to authenticated;

create policy "staff read devices of their branches" on public.devices
  for select to authenticated
  using (branch_id in (select app.accessible_branch_ids()));

create policy "device managers edit devices" on public.devices
  for update to authenticated
  using ((select app.has_permission('devices.manage')) and branch_id in (select app.accessible_branch_ids()))
  with check ((select app.has_permission('devices.manage')) and branch_id in (select app.accessible_branch_ids()));

create policy "device managers read device status" on public.device_status
  for select to authenticated
  using (
    (select app.has_permission('devices.manage'))
    and exists (
      select 1 from public.devices d
       where d.id = device_status.device_id
         and d.branch_id in (select app.accessible_branch_ids())
    )
  );

-- Registers this device in a branch and gives it the next free code. Calling it again with the same
-- device id returns the existing device (safe to retry after a lost response).
create function public.register_device(
  p_device_id uuid,
  p_branch_id uuid,
  p_name text,
  p_platform text,
  p_default_language public.language_code default null
)
returns public.devices
language plpgsql
security definer
set search_path = ''
as $$
declare
  device public.devices;
  next_number integer;
begin
  if not (app.has_permission('devices.manage') and app.has_branch_access(p_branch_id)) then
    raise exception using errcode = '42501', message = 'not_allowed',
      detail = 'Registering a device needs devices.manage and access to its branch';
  end if;

  select * into device from public.devices d where d.id = p_device_id;
  if found then
    if device.branch_id <> p_branch_id then
      raise exception using errcode = '23514', message = 'device_in_other_branch',
        detail = 'This device is already registered in another branch';
    end if;
    return device;
  end if;

  -- One registration at a time per branch, so two devices never get the same code.
  perform pg_advisory_xact_lock(hashtextextended('register_device:' || p_branch_id::text, 0));
  select coalesce(max(substring(d.code from 2)::integer), 0) + 1
    into next_number
    from public.devices d
   where d.branch_id = p_branch_id;

  insert into public.devices (id, branch_id, code, name, platform, default_language)
  values (p_device_id, p_branch_id, 'D' || lpad(next_number::text, 2, '0'), p_name, p_platform, p_default_language)
  returning * into device;
  return device;
end
$$;

-- Called by a device whenever it is online, with its version and upload queue state.
create function public.device_heartbeat(
  p_device_id uuid,
  p_app_version text,
  p_pending_changes integer,
  p_pending_since timestamptz
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.devices d
     where d.id = p_device_id and d.deleted_at is null and app.has_branch_access(d.branch_id)
  ) then
    raise exception using errcode = '42501', message = 'device_not_accessible',
      detail = 'The device does not exist or is in a branch you cannot access';
  end if;

  insert into public.device_status
    (device_id, last_seen_at, last_seen_by, app_version, pending_changes, pending_since)
  values (
    p_device_id,
    now(),
    auth.uid(),
    p_app_version,
    greatest(coalesce(p_pending_changes, 0), 0),
    least(p_pending_since, now())
  )
  on conflict (device_id) do update set
    last_seen_at = excluded.last_seen_at,
    last_seen_by = excluded.last_seen_by,
    app_version = excluded.app_version,
    pending_changes = excluded.pending_changes,
    pending_since = excluded.pending_since;
end
$$;

revoke execute on function public.register_device(uuid, uuid, text, text, public.language_code) from public, anon;
revoke execute on function public.device_heartbeat(uuid, text, integer, timestamptz) from public, anon;
grant execute on function public.register_device(uuid, uuid, text, text, public.language_code) to authenticated, service_role;
grant execute on function public.device_heartbeat(uuid, text, integer, timestamptz) to authenticated, service_role;

-- Settings ------------------------------------------------------------------------------------

-- True when value is a JSON whole number between min_value and max_value.
create function app.is_json_integer(value jsonb, min_value integer, max_value integer)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select case
    when jsonb_typeof(value) = 'number' then
      value::numeric = trunc(value::numeric) and value::numeric between min_value and max_value
    else false
  end
$$;

-- The known setting keys and their allowed values. Later migrations replace this function to add
-- keys. The app has the same rules (and the defaults) in packages/core.
create function app.is_valid_setting(setting_key text, value jsonb)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select case setting_key
    -- Wrong PIN tries before the device asks for the password again.
    when 'security.pin_max_attempts' then app.is_json_integer(value, 3, 10)
    -- Minutes without activity before the app locks.
    when 'security.idle_lock_minutes' then app.is_json_integer(value, 1, 240)
    -- Hours of unsynced data on a device before managers are alerted.
    when 'sync.unsynced_alert_hours' then app.is_json_integer(value, 1, 168)
    else false
  end
$$;

-- A setting without a branch applies to every branch; a branch's own row overrides it. A missing
-- row means the default. Rows are removed (not soft-deleted) to go back to the default; the audit
-- log keeps the history.
create table public.settings (
  id uuid primary key default gen_random_uuid(),
  branch_id uuid references public.branches (id),
  key text not null,
  value jsonb not null,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  unique nulls not distinct (branch_id, key),
  constraint settings_valid_value check (app.is_valid_setting(key, value))
);

create trigger read_only before update on public.settings
  for each row execute function app.read_only_columns('id', 'branch_id', 'key');
create trigger stamp before insert or update on public.settings
  for each row execute function app.stamp_row();
create trigger audit after insert or update or delete on public.settings
  for each row execute function app.audit_row();

alter table public.settings enable row level security;
revoke all on table public.settings from anon, authenticated;
grant all on table public.settings to service_role;
grant select, insert, update, delete on table public.settings to authenticated;

-- Staff read the settings that apply to them. settings.edit changes their branches' settings;
-- settings for every branch also need access to all branches.
create policy "staff read their settings" on public.settings
  for select to authenticated
  using (
    (select app.is_active_staff())
    and (branch_id is null or branch_id in (select app.accessible_branch_ids()))
  );

create policy "setting editors add settings" on public.settings
  for insert to authenticated
  with check (
    (select app.has_permission('settings.edit'))
    and (case when branch_id is null then (select app.has_all_branches())
              else branch_id in (select app.accessible_branch_ids()) end)
  );

create policy "setting editors change settings" on public.settings
  for update to authenticated
  using (
    (select app.has_permission('settings.edit'))
    and (case when branch_id is null then (select app.has_all_branches())
              else branch_id in (select app.accessible_branch_ids()) end)
  )
  with check (
    (select app.has_permission('settings.edit'))
    and (case when branch_id is null then (select app.has_all_branches())
              else branch_id in (select app.accessible_branch_ids()) end)
  );

create policy "setting editors remove settings" on public.settings
  for delete to authenticated
  using (
    (select app.has_permission('settings.edit'))
    and (case when branch_id is null then (select app.has_all_branches())
              else branch_id in (select app.accessible_branch_ids()) end)
  );
